name: Recovery Sync and Debug

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: 'MANIFEST_URL'
        required: true
        default: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp'
      MANIFEST_BRANCH:
        description: 'MANIFEST_BRANCH'
        required: true
        default: 'twrp-12.1'
        
jobs:
  sync_and_debug:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-24.04
    steps:
    - name: Check Out
      uses: actions/checkout@v4

    - name: Cleanup Workspace
      uses: rokibhasansagar/slimhub_actions@main

    - name: Prepare environment
      run: |
        sudo apt update
        sudo apt install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev \
            gcc-multilib g++-multilib libc6-dev-i386 \
            x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils \
            xsltproc unzip fontconfig python3

    - name: Setup SSH Keys
      if: ${{ startsWith(github.event.inputs.MANIFEST_URL, 'git@github.com') }}
      uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Initialize repo
      run: |
        mkdir workspace
        cd workspace
        git config --global user.name "Nico170420"
        git config --global user.email "b170420nc@gmail.com"
        repo init --depth=1 -u ${{ github.event.inputs.MANIFEST_URL }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}
      id: pwd

    - name: Repo Sync
      run: |
        repo sync -j$(nproc --all) --force-sync
      working-directory: workspace

    - name: Clone device tree
      run: |

       git clone -b a32x-twrp https://github.com/Yenping0001/android_device_samsung_a32x.git device/samsung/a32x
      working-directory: workspace

    - name: Clone common tree
      if: github.event.inputs.COMMON_TREE_URL != ''
      run: |
        git clone ${{ github.event.inputs.COMMON_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.COMMON_PATH }}
      working-directory: workspace

    - name: SSH Debugging Session (tmate)
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
        
